import type { Question } from './domain';
const source = 'Özgün örnek • uzman incelemesi bekliyor';
const aidReference = 'https://orduiasb.saglik.gov.tr/TR-138775/112-acil-yardim-arandiginda-nasil-konusulmali.html';
export const additionalQuestions: Question[] = [
  { id: 'original-traffic-3', topic: 'Trafik ve çevre', subtopic: 'Görüş koşulları', text: 'Sis yoğunlaştığı için ilerideki araçları görmek zorlaşıyor. Sürücünün önceliği ne olmalıdır?', options: ['Öndeki aracın tamponuna yaklaşmak', 'Görüşe uygun hıza düşmek', 'Uzun farları sürekli yakmak', 'Yolun ortasını takip etmek'], correct: 1, explanation: 'Hız, görülebilen mesafede güvenle durmaya uygun olmalıdır. Yakın takip sisli havada riski artırır.', source },
  { id: 'original-traffic-4', topic: 'Trafik ve çevre', subtopic: 'Güvenli manevra', text: 'Sürücü sinyal verdiği hâlde yan şeritte bir araç olduğunu fark ediyor. Nasıl davranmalıdır?', options: ['Sinyal verdiği için hemen geçmeli', 'Kornayla aracı uzaklaştırmalı', 'Yan aracı sıkıştırmalı', 'Güvenli boşluk oluşana kadar beklemeli'], correct: 3, explanation: 'Sinyal niyeti bildirir; tek başına geçiş hakkı sağlamaz. Manevra öncesinde çevre kontrolü sürdürülür.', source },
  { id: 'original-traffic-5', topic: 'Trafik ve çevre', subtopic: 'Dikkat ve yorgunluk', text: 'Uzun yolculukta göz kapakları ağırlaşan sürücü için en güvenli tercih nedir?', options: ['Uygun bir dinlenme alanında mola vermek', 'Müziğin sesini yükseltmek', 'Varışa kadar hızını artırmak', 'Camı açıp aynı şekilde devam etmek'], correct: 0, explanation: 'Uykululuk güvenli sürüşü bozar. Cam açmak veya müzik dinlemek dinlenmenin yerini tutmaz.', source },
  { id: 'original-aid-3', topic: 'İlk yardım', subtopic: 'Acil çağrıda konum', referenceUrl: aidReference, text: 'Kazayı 112’ye bildirirken ekiplerin doğru yere ulaşmasını hangi bilgi kolaylaştırır?', options: ['Aracın satın alındığı tarih', 'Yolculuğun amacı', 'Açık konum ve yakındaki belirgin bir yer', 'Sürücünün mesleği'], correct: 2, explanation: 'Konumun anlaşılır biçimde tarif edilmesi, yakın bir okul veya kavşak gibi belirgin noktaların belirtilmesi ekiplerin ulaşmasına yardımcı olur.', source },
  { id: 'original-aid-4', topic: 'İlk yardım', subtopic: 'Acil çağrıda iletişim', referenceUrl: aidReference, text: '112 görevlisi olayla ilgili ek sorular sorarken arayan kişi ne yapmalıdır?', options: ['Konumu söyledikten sonra telefonu kapatmalı', 'Soruları yanıtlayıp görevlinin yönlendirmesini beklemeli', 'Telefonu başka bir arama için kapatmalı', 'Görevlinin sözünü sürekli kesmeli'], correct: 1, explanation: 'Görevli görüşmenin tamamlandığını belirtmeden hat kapatılmaz; ek bilgiler yardımın düzenlenmesini destekler.', source },
  { id: 'original-aid-5', topic: 'İlk yardım', subtopic: 'Olay yeri güvenliği', referenceUrl: 'https://goynukdh.saglik.gov.tr/TR-740643/ilk-yardimin-temel-uygulamalari-nelerdir.html', text: 'Kaza alanında yakıt sızıntısı fark ediliyor. Çevredeki kişiler hangi davranıştan kaçınmalıdır?', options: ['Acil yardım istemekten', 'Tehlikeyi diğer kişilere bildirmekten', 'Güvenli mesafeye geçmekten', 'Sigara yakmaktan'], correct: 3, explanation: 'Yakıt yakınındaki ateş ve kıvılcım yangına yol açabilir. Olay yerinde sigara içilmesine izin verilmemelidir.', source },
  { id: 'original-car-3', topic: 'Araç tekniği', subtopic: 'Yağlama sistemi', text: 'Motor yağı, hareketli parçalar arasında hangi temel görevi yerine getirir?', options: ['Egzoz gazını depolamak', 'Lastiğin yol tutuşunu artırmak', 'Sürtünme ve aşınmayı azaltmak', 'Aküyü şarj etmek'], correct: 2, explanation: 'Yağ, hareketli yüzeyler arasında koruyucu bir tabaka oluşturarak sürtünme ve aşınmanın azalmasına yardımcı olur.', source },
  { id: 'original-car-4', topic: 'Araç tekniği', subtopic: 'Silecekler', text: 'Yağmurda silecekler camda belirgin izler bırakıyor. Hangi işlem doğrudan bu sorunla ilgilidir?', options: ['Silecek lastiklerini kontrol etmek', 'Korna sesini artırmak', 'Koltuk yüksekliğini azaltmak', 'Yakıt deposunu doldurmak'], correct: 0, explanation: 'Kirli veya yıpranmış silecek lastikleri camı yeterince temizleyemez. Görüşü etkileyen bu durum giderilmelidir.', source },
  { id: 'original-car-5', topic: 'Araç tekniği', subtopic: 'Lastik kontrolü', text: 'Yola çıkmadan lastiğin yan yüzeyinde şişkinlik görülüyor. Sürücü ne yapmalıdır?', options: ['Lastiğin havasını artırıp devam etmeli', 'Lastiği uzman servise kontrol ettirmeli', 'Şişkinliği keserek düzeltmeli', 'Yalnızca lastiği yıkamalı'], correct: 1, explanation: 'Yan yüzeyde şişkinlik lastiğin yapısal hasarına işaret edebilir. Güvenli kullanım için uzman kontrolü gerekir.', source },
  { id: 'original-manners-3', topic: 'Trafik adabı', subtopic: 'Sabır', text: 'Önünüzdeki sürücü park manevrasını yavaş tamamlıyor. Hangi yaklaşım trafik adabına uygundur?', options: ['Camdan bağırmak', 'Araca iyice yaklaşmak', 'Aralıksız korna çalmak', 'Güvenli mesafede sabırla beklemek'], correct: 3, explanation: 'Baskı kurmak hata ihtimalini artırabilir. Sabırlı davranmak herkesin güvenli hareket etmesini destekler.', source },
  { id: 'original-manners-4', topic: 'Trafik adabı', subtopic: 'Öfke kontrolü', text: 'Bir başka sürücünün davranışı sizi öfkelendirdi. En uygun tepki hangisidir?', options: ['Mesafeyi koruyup dikkati yola vermek', 'Aracı takip ederek hesap sormak', 'Önüne geçip fren yapmak', 'Aynı davranışla karşılık vermek'], correct: 0, explanation: 'Tartışma ve misilleme tehlikeyi büyütür. Güvenli mesafeyi korumak ve sürüşe odaklanmak daha güvenlidir.', source },
  { id: 'original-manners-5', topic: 'Trafik adabı', subtopic: 'Paylaşılan alanlar', text: 'Bir sürücü aracını kaldırımdaki erişim rampasını kapatacak şekilde bırakmayı düşünüyor. Hangi düşünce bu karardan vazgeçmesini sağlamalıdır?', options: ['Aracın rengi çevreye uymuyor', 'Kısa süreceği için kimse etkilenmez', 'Rampa, hareket kısıtlılığı olan kişilerin geçişi için gerekli', 'Yalnızca diğer otomobillerin geçmesi yeterli'], correct: 2, explanation: 'Trafikte diğer kullanıcıların ihtiyaçlarını gözetmek gerekir. Rampanın kapanması tekerlekli sandalye ve bebek arabası kullananların geçişini engelleyebilir.', source },
];
