import { examQuestions } from './examQuestions';
import { pdfQuestions } from './pdfQuestions';
import { additionalQuestions } from './additionalQuestions';
import type { Question } from './domain';
const source = 'Özgün örnek • uzman incelemesi bekliyor';
// PDF soruları kaynak bilgisiyle, özgün örnekler ayrı kimlikleriyle korunur.
export const questions: Question[] = [...pdfQuestions, ...examQuestions, ...additionalQuestions,
  { id: 'demo-traffic-1', topic: 'Trafik ve çevre', text: 'Yağış nedeniyle yol kayganlaştığında sürücü nasıl davranmalıdır?', options: ['Takip mesafesini azaltmalı', 'Hızını artırmalı', 'Hızını azaltıp takip mesafesini artırmalı', 'Ani fren yaparak ilerlemeli'], correct: 2, explanation: 'Kaygan zemin tutunmayı azaltır. Hızı düşürmek ve daha fazla mesafe bırakmak güvenli duruş için alan sağlar.', source },
  { id: 'demo-aid-1', topic: 'İlk yardım', text: 'Bir trafik kazası için acil yardım çağrısı hangi numaradan yapılır?', options: ['112', '182', '170', '184'], correct: 0, explanation: '112, acil yardım çağrıları için kullanılan ortak numaradır. Konum ve olay bilgisi açıkça aktarılmalıdır.', source },
  { id: 'demo-car-1', topic: 'Araç tekniği', text: 'Lastik hava basıncı için hangi değer esas alınmalıdır?', options: ['Yan araçtaki lastiğin basıncı', 'Araç üreticisinin önerdiği değer', 'Her araç için aynı sabit değer', 'Lastiğin görünüşüne göre tahmin edilen değer'], correct: 1, explanation: 'Doğru basınç araç ve yük durumuna göre değişebilir. Üreticinin kılavuzundaki veya araç üzerindeki etiketindeki değer esas alınır.', source },
  { id: 'demo-manners-1', topic: 'Trafik adabı', text: 'Bir sürücü trafikte hata yaptığında diğer sürücünün uygun yaklaşımı hangisidir?', options: ['Israrla korna çalmak', 'Aracı yakından takip etmek', 'Önünü kesmek', 'Sakin kalıp güvenli mesafeyi korumak'], correct: 3, explanation: 'Sakin kalmak ve güvenli mesafeyi korumak, hatanın başka bir tehlikeye dönüşmesini önlemeye yardımcı olur.', source },
  { id: 'demo-traffic-2', topic: 'Trafik ve çevre', text: 'Yakıt tüketimini ve çevreye verilen zararı azaltmaya hangi davranış katkı sağlar?', options: ['Gereksiz yere motoru rölantide çalıştırmak', 'Aracın bakımını düzenli yaptırmak', 'Sürekli ani hızlanmak', 'Lastik basıncını önerilenin altında tutmak'], correct: 1, explanation: 'Düzenli bakım, aracın verimli çalışmasını destekler. Gereksiz rölanti ve ani hızlanmalar tüketimi artırır.', source },
  { id: 'demo-aid-2', topic: 'İlk yardım', text: 'Kazaya yardım etmek için duran kişi önce neye dikkat etmelidir?', options: ['Olayı sosyal medyada paylaşmaya', 'Hasarlı araçları incelemeye', 'Kendisinin ve olay yerinin güvenliğine', 'Trafiğin ortasında beklemeye'], correct: 2, explanation: 'Yardım eden kişinin ve olay yerinin güvenliği, yeni kazaların ve yaralanmaların önlenmesi için önceliklidir.', source },
  { id: 'demo-car-2', topic: 'Araç tekniği', text: 'Motor sıcaklığı tehlikeli biçimde yükselirse hangi davranış uygundur?', options: ['Güvenli bir yerde durup araç kılavuzundaki talimatları izlemek', 'Yola daha yüksek hızla devam etmek', 'Sıcakken soğutma sistemi kapağını hemen açmak', 'Uyarıyı görmezden gelmek'], correct: 0, explanation: 'Güvenli bir yerde durulmalı ve üretici talimatları izlenmelidir. Sıcak ve basınçlı soğutma sisteminin kapağını açmak yanıklara neden olabilir.', source },
  { id: 'demo-manners-2', topic: 'Trafik adabı', text: 'Trafikte empati kurmak ne anlama gelir?', options: ['Yalnızca kendi zamanını önemsemek', 'Her durumda geçiş önceliği istemek', 'Diğer sürücülere üstünlük kurmak', 'Diğer yol kullanıcılarının durumunu da düşünmek'], correct: 3, explanation: 'Empati; yayaların, bisikletlilerin ve diğer sürücülerin ihtiyaçlarını ve karşılaşabilecekleri güçlükleri dikkate almaktır.', source },
];
